feat: add option to disable the creation of new, empty redirects (fixes: #18)
tinect/TinectRedirects pull request #21
Opened 2024-01-10 16:53 UTC by jeboehm

2024-01-11 09:11 UTC, tinect commented
Thank you. I like this! 👍 

As discussed in slack, would you like to migrate the config-request into the subscriber and forward its value into the message?

2024-01-11 09:12 UTC, tinect requested changes
Thank you. I like this! 👍

As discussed in slack, would you like to migrate the config-request into the subscriber and forward its value into the message?

2024-01-11 10:17 UTC, jeboehm commented
Sorry, this escalated :D

2024-01-11 20:57 UTC, tinect commented on src/Message/TinectRedirectUpdateHandler.php
> +                      ON DUPLICATE KEY UPDATE `count` = count + 1, `updated_at` = NOW()'
nice catch 👍

2024-01-11 21:08 UTC, tinect commented on src/Subscriber/ExceptionSubscriber.php
> +        if ($redirect === null || !$redirect->isActive()) {
Thank you for reducing the cognitive complexity

2024-01-12 22:32 UTC, tinect approved these changes

2024-01-12 22:33 UTC, merged

2024-01-12 22:37 UTC, tinect commented
Thank you! :-)