feat: refactor admin component
tinect/TinectRedirects pull request #28
Opened 2024-02-24 12:41 UTC by stefanpoensgen

2024-02-24 23:16 UTC, tinect commented
Thank you, @stefanpoensgen 

When filtering by term, the request is sent twice. Do you have an idea?

2024-02-24 23:24 UTC, tinect requested changes

2024-02-24 23:24 UTC, tinect commented on src/Resources/app/administration/src/module/tinect-redirects/page/tinect-redirects-index/template.html.twig
> +                            {{ $tc('tinect-redirects.sidebar.filters.resetFilter') }}
```suggestion
                            {{ $tc('tinect-redirects.sidebar.filter.resetFilter') }}
```

2024-02-25 21:07 UTC, stefanpoensgen commented
> Additionally, How does this solve #14 ? I don't see any different.
nvm. it does not ^^

2024-02-25 21:13 UTC, stefanpoensgen commented
> When filtering by term, the request is sent twice. Also any detail page is sending it twice. Do you have an idea?

@tinect fixed

2024-02-25 21:27 UTC, tinect requested changes

2024-02-25 21:27 UTC, tinect commented on src/Resources/app/administration/src/module/tinect-redirects/page/tinect-redirects-index/index.js
> +            }
```suggestion
            criteria.addFilter(Criteria.equals('hidden', this.filter.hidden));
```

This change needs to be reverted. You filter on active, and this filter should always trigger, while default should not show hidden contents

2024-02-25 23:20 UTC, merged